@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Create User
POST http://{{host}}/users/create HTTP/1.1
Content-Type: {{contentType}}

  {
    "fullName": "fvdavid2",
    "password": "123456789",
    "email": "fv@halunix.com"
  }


### Get All Users
GET http://{{host}}/users HTTP/1.1

### Get One User
GET http://{{host}}/users/61474e5084a30eabb07347b333 HTTP/1.1
